### ISSUE TITLE
@conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by bgruening** [conda-forge/r-europepmc-feedstock#2]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by dpryan79** [comment]
You can probably just rerun the circleci job for this, it appears to have been a temporary failure.

**Comment by bgruening** [comment]
Nice catch. Done and relabled.
